# Generated by Django 2.0.1 on 2018-03-05 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedev',
            old_name='groupToDevice',
            new_name='GroupToDevice',
        ),
        migrations.AlterField(
            model_name='port',
            name='mainswitchport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coordinator.MainSwitchPort'),
        ),
    ]
