# Generated by Django 2.0.1 on 2018-03-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptodevice',
            name='adminNotifSeenStatus',
            field=models.CharField(choices=[('SE', 'SE'), ('US', 'US')], default='US', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='grouptodevice',
            name='userNotifSeenStatus',
            field=models.CharField(choices=[('SE', 'SE'), ('US', 'US')], default='SE', max_length=2, null=True),
        ),
    ]
