# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-13 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employeeID',
            field=models.CharField(max_length=10),
        ),
    ]
