# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-01 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='usertype',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], max_length=10),
        ),
    ]
