# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-03 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0002_auto_20171101_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptodevice',
            name='type',
            field=models.CharField(choices=[('RS', 'Reserve'), ('AP', 'Approve'), ('AL', 'Allocation'), ('DC', 'Declined')], max_length=2),
        ),
    ]
