# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-16 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0002_saveconn_savetopology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveconn',
            old_name='destDevID',
            new_name='endDevice',
        ),
        migrations.RenameField(
            model_name='saveconn',
            old_name='destDevPort',
            new_name='endPort',
        ),
        migrations.RenameField(
            model_name='saveconn',
            old_name='srcDevID',
            new_name='srcDevice',
        ),
        migrations.RenameField(
            model_name='saveconn',
            old_name='srcDevPort',
            new_name='srcPort',
        ),
        migrations.AddField(
            model_name='saveconn',
            name='connectionName',
            field=models.CharField(default='old', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saveconn',
            name='cableType',
            field=models.IntegerField(),
        ),
    ]
