# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-10 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0002_auto_20171010_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userID',
            field=models.CharField(default=0, max_length=10, unique=True),
        ),
    ]
