# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-22 00:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Coordinator', '0002_auto_20170921_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('branch', models.CharField(max_length=50)),
                ('usertype', models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee')], max_length=10)),
                ('idnum', models.IntegerField()),
                ('userID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='logs',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coordinator.UserProfile'),
        ),
        migrations.AlterField(
            model_name='usertogroup',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coordinator.UserProfile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
