# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-16 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0003_auto_20171116_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveconn',
            name='cableType',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='saveconn',
            name='endDevice',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='saveconn',
            name='endPort',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='saveconn',
            name='srcDevice',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='saveconn',
            name='srcPort',
            field=models.CharField(max_length=25),
        ),
    ]
