# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-22 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0003_auto_20170922_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='idnum',
        ),
    ]
