# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-17 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0004_auto_20171116_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='action',
            field=models.CharField(default='blank', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='device',
            field=models.CharField(max_length=40),
        ),
    ]
